all: Q1_floatbench Q1_matrixbench Q1_intbench

Q1_floatbench: Q1_floatbench.cpp
	g++ -Wall -g -o Q1_floatbench Q1_floatbench.cpp

Q1_matrixbench: Q1_matrixbench.cpp
	g++ -Wall -g -o Q1_matrixbench Q1_matrixbench.cpp

Q1_intbench: Q1_intbench.cpp
	g++ -Wall -g -o Q1_intbench Q1_intbench.cpp

clean:
	rm Q1_floatbench Q1_matrixbench Q1_intbench